#!/bin/sh

latest=$(curl -sSL https://api.github.com/repos/kubernetes-sigs/node-feature-discovery/releases/latest | jq -r .name)

kubectl kustomize \
  "https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=$latest" > "nfd.yaml"
